### ISSUE TITLE
聊天字库部分词典不生效

### ISSUE THREAD

**Issue by chivesssss** [ssnhd/rime#48]
**不知道是不是没有标明索引顺序的原因**

<img width="703" alt="Xnip2022-01-11_17-25-17" src="https://user-images.githubusercontent.com/23553358/148916639-88140601-567c-485e-8308-26dfd4509808.png">
<img width="628" alt="Xnip2022-01-11_17-26-44" src="https://user-images.githubusercontent.com/23553358/148916648-8ac8de1b-b3ca-4889-a4a8-8807b0b6260e.png">

**Comment by xhql** [comment]
无法复现，你在后面加个数字试试，如果是这个原因，请告知。

**Comment by crazywhalecc** [comment]
![image](https://user-images.githubusercontent.com/20330940/150902651-374c0a01-5f97-4fda-98b3-c8ef6c5d0a1c.png)
![image](https://user-images.githubusercontent.com/20330940/150902685-b3f5d69e-95fd-42e5-9b94-7f3b2741acc7.png)
![image](https://user-images.githubusercontent.com/20330940/150902711-81514f80-7901-4c3d-9daa-cb109af2a093.png)
![image](https://user-images.githubusercontent.com/20330940/150902789-8cffd76d-11bd-4a9f-8dee-601447bbd23d.png)

这种情况是什么造成的，我打这句也是候选好多次才打正确。

**Comment by ssnhd** [comment]
> ![image](https://user-images.githubusercontent.com/20330940/150902651-374c0a01-5f97-4fda-98b3-c8ef6c5d0a1c.png) ![image](https://user-images.githubusercontent.com/20330940/150902685-b3f5d69e-95fd-42e5-9b94-7f3b2741acc7.png) ![image](https://user-images.githubusercontent.com/20330940/150902711-81514f80-7901-4c3d-9daa-cb109af2a093.png) ![image](https://user-images.githubusercontent.com/20330940/150902789-8cffd76d-11bd-4a9f-8dee-601447bbd23d.png) ![image](https://user-images.githubusercontent.com/20330940/150902837-a7b2c5c7-5fd8-4974-aaa6-1928e9ac6fcc.png)
> 
> 这种情况是什么造成的，我打这句也是候选好多次才打正确。上面这些前面的词从来没打过。

无法复现，建议备份个人词库，重新下载配置部署

**Comment by crazywhalecc** [comment]
> 无法复现，建议备份个人词库，重新下载配置部署

目前主要是使用了朙月拼音的词库部份和英文部份，`luna_pinyin_simp.custom.yaml` 配置文件如下：

```yaml
# 这个文件用于【朙月拼音简化字】的相关配置选项
patch:
  punctuator: 
    # 这个貌似是用于朙月拼音简化字的预置符号的
    import_preset: symbols
    # 这些是额外加出来的直接上屏的符号们
    half_shape:
      "#": "#"
      "*": "*"
      "`": "`"
      "~": "~"
      "@": "@"
      "=": "="
      '\': "、"
      "/": "/"
      "%": "%"
      "$": "¥"
      "|": ["|", "｜", "·"]
      "[": "【"
      "]": "】"
      "<": "《"
      ">": "》"
  # 启用罕见字過濾
  engine/filters:
    - simplifier
    - simplifier@emoji_conversion
    - uniquifier
    - charset_filter@gbk # (※3) GBK 过滤
    - single_char_filter
  # 改写拼写运算，含英文的词汇（luna_pinyin.cn_en.dict.yaml）不影响简拼
  "speller/algebra/@before 0": xform/^([b-df-hj-np-tv-z])$/$1_/
  # 载入朙月拼音扩充词库
  "translator/dictionary": luna_pinyin.extended
  # 加载easy_en依赖
  "schema/dependencies/@1": easy_en
  # 载入翻译英文的码表翻译器，取名为 english
  "engine/translators/@4": table_translator@english
  # english翻译器的设定项
  english:
    dictionary: easy_en
    spelling_hints: 9
    enable_completion: false # 是否启用英文输入联想补全
    enable_sentence: false # 混输时不出现带有图案的英文
    initial_quality: -0.5 # 英文候选词的位置, 数值越大越靠前。
  # 模糊拼音
  "speller/algebra":
    - erase/^xx$/ # 第一行保留

    # 模糊音定義先於簡拼定義，方可令簡拼支持以上模糊音
    - abbrev/^([a-z]).+$/$1/ # 簡拼（首字母）
    - abbrev/^([zcs]h).+$/$1/ # 簡拼（zh, ch, sh）
```

对于词库扩展，我是直接复制粘贴进来的，文件 `luna_pinyin.extended.dict.yaml`：

```yaml
# Rime dictionary
# encoding: utf-8
# Luna Pinyin Extended Dictionary(Basic)  - 明月拼音扩充词库（基本）

---
name: luna_pinyin.extended      # 词库名
version: "2021.02.07"
sort: by_weight                 # by_weight（按词频高低排序）或 original（保持原码表中的顺序）
use_preset_vocabulary: true     # true 或 false，选择是否导入预设词汇表【八股文】

import_tables:
  - luna_pinyin
  - luna_pinyin.chat
  - luna_pinyin.chengshi
  - luna_pinyin.gongcheng
  - luna_pinyin.nongye
  - luna_pinyin.renwen
  - luna_pinyin.shehui
  - luna_pinyin.shenghuo
  - luna_pinyin.yishu
  - luna_pinyin.yixue
  - luna_pinyin.youxi
  - luna_pinyin.yule
  - luna_pinyin.yundong
  - luna_pinyin.ziran
```
