### ISSUE TITLE
希望添加 color_scheme_dark 选项，以响应 Mac 系统明暗色主题变化

### ISSUE THREAD

**Issue by wsmbsbbz** [ssnhd/rime#57]
Squirrel 支持根据 Mac 系统明暗色主题自动切换输入法主题，希望能在 `squirrel.custom.yaml` 中添加这个选项，只需要做一点小改动即可，大致如下：

```yaml
  # 皮肤主题名称输入在下方，开启去掉前面#
  # 浅色主题
  #style/color_scheme: mac_light
  #style/color_scheme: mac_green
  #style/color_scheme: mac_orange
  #style/color_scheme: mac_blue
  #style/color_scheme: win10
  #style/color_scheme: apathy
  #style/color_scheme: google
  style/color_scheme: milan
  #style/color_scheme: ink
  #style/color_scheme: nord_light
  # 暗色主题
  style/color_scheme_dark: mac_dark
  #style/color_scheme_dark: psionics
  #style/color_scheme_dark: solarized_rock
  #style/color_scheme_dark: solarized_dark
  #style/color_scheme_dark: purity
  #style/color_scheme_dark: starcraft
  #style/color_scheme_dark: nord_dark
```
